import { pgTable, text, serial, integer, boolean, timestamp, jsonb, doublePrecision } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Users table
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  apiKey: text("api_key"),
  apiSecret: text("api_secret"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const insertUserSchema = createInsertSchema(users).pick({
  username: true,
  password: true,
  apiKey: true,
  apiSecret: true,
});

// Trading positions table
export const positions = pgTable("positions", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  symbol: text("symbol").notNull(),
  positionAmt: text("position_amt").notNull(),
  entryPrice: text("entry_price").notNull(),
  markPrice: text("mark_price").notNull(),
  unRealizedProfit: text("unrealized_profit").notNull(),
  liquidationPrice: text("liquidation_price").notNull(),
  leverage: text("leverage").notNull(),
  marginType: text("margin_type").notNull(),
  positionSide: text("position_side").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertPositionSchema = createInsertSchema(positions).pick({
  userId: true,
  symbol: true,
  positionAmt: true,
  entryPrice: true,
  markPrice: true,
  unRealizedProfit: true,
  liquidationPrice: true,
  leverage: true,
  marginType: true,
  positionSide: true,
});

// Trading orders table
export const orders = pgTable("orders", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  symbol: text("symbol").notNull(),
  orderId: text("order_id").notNull(),
  clientOrderId: text("client_order_id").notNull(),
  side: text("side").notNull(),
  type: text("type").notNull(),
  quantity: text("quantity").notNull(),
  price: text("price"),
  stopPrice: text("stop_price"),
  status: text("status").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertOrderSchema = createInsertSchema(orders).pick({
  userId: true,
  symbol: true,
  orderId: true,
  clientOrderId: true,
  side: true,
  type: true,
  quantity: true,
  price: true,
  stopPrice: true,
  status: true,
});

// Trading strategies table
export const strategies = pgTable("strategies", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  name: text("name").notNull(),
  type: text("type").notNull(),
  params: jsonb("params").notNull(),
  isActive: boolean("is_active").notNull().default(false),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const insertStrategySchema = createInsertSchema(strategies).pick({
  userId: true,
  name: true,
  type: true,
  params: true,
  isActive: true,
});

// Trading signals table - stores all signals generated by the system
export const tradingSignals = pgTable("trading_signals", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id),
  externalId: text("external_id").unique(),
  symbol: text("symbol").notNull(),
  direction: text("direction").notNull(), // 'LONG' or 'SHORT'
  timeframe: text("timeframe").notNull(), // e.g., '5m', '1h', '4h'
  strategyType: text("strategy_type").notNull(),
  entryPrice: doublePrecision("entry_price").notNull(),
  stopLoss: doublePrecision("stop_loss").notNull(),
  takeProfit: doublePrecision("take_profit").notNull(),
  riskRewardRatio: doublePrecision("risk_reward_ratio").notNull(),
  confidence: doublePrecision("confidence").notNull(), // 0-100
  score: doublePrecision("score").notNull(), // 0-100
  executed: boolean("executed").default(false),
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  marketRegime: text("market_regime"), // 'TRENDING', 'RANGING', 'VOLATILE', 'NEUTRAL'
  technicalIndicators: jsonb("technical_indicators"), // RSI, MACD, etc.
  additionalData: jsonb("additional_data"), // Any additional analysis data
});

export const insertTradingSignalSchema = createInsertSchema(tradingSignals).pick({
  userId: true,
  externalId: true,
  symbol: true,
  direction: true,
  timeframe: true,
  strategyType: true,
  entryPrice: true,
  stopLoss: true,
  takeProfit: true,
  riskRewardRatio: true,
  confidence: true,
  score: true,
  executed: true,
  marketRegime: true,
  technicalIndicators: true,
  additionalData: true,
});

// Market regimes table - stores the current market regime for each symbol/timeframe
export const marketRegimes = pgTable("market_regimes", {
  id: serial("id").primaryKey(),
  symbol: text("symbol").notNull(),
  timeframe: text("timeframe").notNull(),
  regime: text("regime").notNull(), // 'TRENDING', 'RANGING', 'VOLATILE', 'NEUTRAL'
  strength: doublePrecision("strength").notNull(), // 0-100
  direction: text("direction"), // 'UP', 'DOWN', null for ranging/neutral
  timestamp: timestamp("timestamp").defaultNow().notNull(),
  indicators: jsonb("indicators"), // Indicators used to determine regime
});

export const insertMarketRegimeSchema = createInsertSchema(marketRegimes).pick({
  symbol: true,
  timeframe: true,
  regime: true,
  strength: true,
  direction: true,
  indicators: true,
});

// Trading performance metrics
export const performanceMetrics = pgTable("performance_metrics", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull().references(() => users.id),
  portfolioValue: text("portfolio_value").notNull(),
  dailyPnL: text("daily_pnl").notNull(),
  weeklyPnL: text("weekly_pnl").notNull(),
  totalTrades: integer("total_trades").notNull(),
  winningTrades: integer("winning_trades").notNull(),
  losingTrades: integer("losing_trades").notNull(),
  winRate: integer("win_rate").notNull(),
  maxDrawdown: text("max_drawdown").notNull(),
  sharpeRatio: text("sharpe_ratio").notNull(),
  date: timestamp("date").notNull(),
});

export const insertPerformanceMetricsSchema = createInsertSchema(performanceMetrics).pick({
  userId: true,
  portfolioValue: true,
  dailyPnL: true,
  weeklyPnL: true,
  totalTrades: true,
  winningTrades: true,
  losingTrades: true,
  winRate: true,
  maxDrawdown: true,
  sharpeRatio: true,
  date: true,
});

// Type definitions
export type InsertUser = z.infer<typeof insertUserSchema>;
export type User = typeof users.$inferSelect;

export type InsertPosition = z.infer<typeof insertPositionSchema>;
export type Position = typeof positions.$inferSelect;

export type InsertOrder = z.infer<typeof insertOrderSchema>;
export type Order = typeof orders.$inferSelect;

export type InsertStrategy = z.infer<typeof insertStrategySchema>;
export type Strategy = typeof strategies.$inferSelect;

export type InsertTradingSignal = z.infer<typeof insertTradingSignalSchema>;
export type TradingSignal = typeof tradingSignals.$inferSelect;

export type InsertMarketRegime = z.infer<typeof insertMarketRegimeSchema>;
export type MarketRegime = typeof marketRegimes.$inferSelect;

export type InsertPerformanceMetrics = z.infer<typeof insertPerformanceMetricsSchema>;
export type PerformanceMetrics = typeof performanceMetrics.$inferSelect;
